# Stolen from https://github.com/abarichello/godot-ci

stages:
  - export

variables:
  EXPORT_NAME: AimSolver

linux:
  image: tengkuizdihar/godot-rust-ci:3.2.3-2
  stage: export
  script:
    - mkdir -v -p build/linux
    - cd compegodot
    - cargo build --release
    - cp compegodot_library.gdnlib.release compegodot_library.gdnlib
    - godot -v --export "Linux X" ../build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

# TODO: windows export is not ready yet because there's no godot-rust-ci-windows
# CLUE: create a windows based godot + rust image

windows:
  stage: export
  script:
    - mkdir %appdata%\Godot\templates\3.2.3.stable
    - Invoke-RestMethod -Uri https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_x11.64.zip -OutFile %appdata%\Godot\templates\3.2.3.stable
    - dir %appdata%\Godot\templates\3.2.3.stable
    - mkdir -v -p build/windows
    - cd compegodot
    - cargo build --target x86_64-pc-windows-gnu
    - godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
  tags:
    - shared-windows
    - windows
    - windows-1809
